DELETE FROM marcas
WHERE nombre IN (
    'CHEVROLET',
    'RENAULT',
    'MAZDA',
    'KIA',
    'TOYOTA',
    'NISSAN',
    'HYUNDAI',
    'FORD',
    'VOLKSWAGEN',
    'SUZUKI',
    'MITSUBISHI',
    'PEUGEOT',
    'CITROEN',
    'FIAT',
    'JEEP',
    'MERCEDES-BENZ',
    'BMW',
    'AUDI',
    'VOLVO',
    'GREAT WALL',
    'JAC',
    'CHANGAN',
    'BYD',
    'FOTON',
    'YAMAHA',
    'HONDA',
    'BAJAJ',
    'AKT',
    'TVS',
    'KYMCO',
    'KAWASAKI',
    'HERO',
    'UM',
    'VICTORY',
    'ROYAL ENFIELD',
    'KTM',
    'DUCATI',
    'SYM',
    'HINO',
    'INTERNATIONAL',
    'KENWORTH',
    'FREIGHTLINER'
);